#
#   DGSOL directory
#

libs: dgvmlm blas csrch utils vmlm

dgvmlm:
	cd src/dgvmlm; make 

blas:
	cd src/blas; make

csrch:
	cd src/csrch; make 

utils:
	cd src/utils; make

vmlm:
	cd src/vmlm; make

clean:
	cd src/dgvmlm; make clean
	cd src/blas;   make clean
	cd src/csrch;  make clean
	cd src/utils;  make clean
	cd src/vmlm;   make clean


